function [deltaff,PSNR,w] = DffCalculationAfterPSNRfiltering(calciumToSpikeParams,w)

%ReadRawFluorAndDff
%This function reads the raw cell fluorescence data from the Fall.mat file
%generated by Suite2p and then creates a matrix containing all the dF/F 
%data by subtracting 70% of the neuropil data from the raw flourescence and
%then calculating the dF/F through a modified version of the median method
%used by the Allen Institute.
%link: https://brainmapportal-live-4cc80a57cd6e400d854-f7fdcae.divio-media.net/filer_public/4e/be/4ebe2911-bd38-4230-86c8-01a86cfd758e/visual_behavior_2p_technical_whitepaper.pdf


load(calciumToSpikeParams.FallDataPath)


%There are several conditions, which if met, would lead to df/f
%calculation: (1)It has to be a cell, (2)It has to have values of cell
%probability higher than the threshold value what was set in the suite2p
%classifier(generally 0.5)


%Calculating PSNR values for all cells. This is done to remove cells having
%PSNR values > 4SD of all the PSNR values

[PSNR] = PSNRcalculation(F,Fneu,isCell,calciumToSpikeParams);

%% temp coding to save necessary data
% save('koko.mat', '-struct', 'calciumToSpikeParams','PSNR')
% save('koko.mat','ops','-append')
%%

[deltaff,w] = DffCalculationForC2Sgui(F,calciumToSpikeParams,isCell,Fneu,PSNR,w);













    
