function RENAMEiscellTOisCell(calciumToSpikeParams)

%This function renames the iscell variable in the Fall.mat file to isCell.
%The Fall.mat file is generated by the Suite2p.

tempVar= load(calciumToSpikeParams.FallDataPath);

isCell = tempVar.iscell;
clearvars tempVar
load(calciumToSpikeParams.FallDataPath);
clear iscell

save('Fall.mat', '-regexp', '^(?!calciumToSpikeParams$).')